name: mpris
description: A library to interface D-Bus MPRIS media players on linux systems.
version: 1.1.0
homepage: https://github.com/jld3103/dart-mpris

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dbus: ^0.7.10
